# Generated by Django 5.1 on 2024-08-12 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jwtauth', '0002_userdata_is_verified_userdata_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='otp',
        ),
    ]
