# Generated by Django 5.1 on 2024-08-13 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwtauth', '0006_noticeimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticeimage',
            name='image',
            field=models.FileField(blank=True, default='', null=True, upload_to='notices'),
        ),
    ]
